# Generated by Django 3.1.7 on 2021-10-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Protecao', '0002_auto_20211015_1523'),
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='protecao',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Protecao.protecao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
